/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.zacharykarpinski.dips;

import com.zacharykarpinski.dips.Snakeyaml;

public class App {
    public String getGreeting() {
        return "Hello World! This is not a safe application. :)";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        // CVE_2022_1471 - To fix, set safe to true or use snakeyaml 2.0
        Snakeyaml snakeyaml = new Snakeyaml();
        snakeyaml.CVE_2022_1471(false);

    }
}
